enableGlobalCache: true

logFilters:
  - code: YN0032
    level: discard

nodeLinker: node-modules

packageExtensions:
  "@algolia/autocomplete-core@*":
    peerDependencies:
      "@algolia/client-search": ^4.9.1
      algoliasearch: ^4.18.0
  "@algolia/autocomplete-plugin-algolia-insights@*":
    peerDependencies:
      "@algolia/client-search": ^4.9.1
      algoliasearch: ^4.18.0
  "@docsearch/react@*":
    dependencies:
      "@algolia/client-search": ^4.9.1
  babel-plugin-transform-flow-enums@*:
    peerDependencies:
      "@babel/core": ^7.0.0
  react-native@*:
    peerDependencies:
      "@babel/preset-env": ^7.1.6

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.8.4.cjs
