compressionLevel: mixed

enableGlobalCache: true

logFilters:
  - code: YN0032
    level: discard

nodeLinker: node-modules

packageExtensions:
  "@algolia/autocomplete-core@*":
    peerDependencies:
      "@algolia/client-search": ^4.9.1
      algoliasearch: ^4.18.0
  "@algolia/autocomplete-plugin-algolia-insights@*":
    peerDependencies:
      "@algolia/client-search": ^4.9.1
      algoliasearch: ^4.18.0
  "@docsearch/react@*":
    dependencies:
      "@algolia/client-search": ^4.9.1
  "@react-native/babel-plugin-codegen@*":
    peerDependencies:
      "@babel/preset-env": ^7.1.6
  "@react-native/babel-preset@*":
    peerDependencies:
      "@babel/preset-env": ^7.1.6
  "@react-native/community-cli-plugin@*":
    peerDependencies:
      "@babel/preset-env": ^7.1.6
  "@react-native/metro-babel-transformer@*":
    peerDependencies:
      "@babel/preset-env": ^7.1.6
  babel-plugin-transform-flow-enums@*:
    peerDependencies:
      "@babel/core": ^7.0.0
  react-native@*:
    peerDependencies:
      "@babel/preset-env": ^7.1.6

yarnPath: .yarn/releases/yarn-4.10.3.cjs
