compressionLevel: mixed

enableGlobalCache: true

enableTelemetry: false

logFilters:
  - code: YN0032
    level: discard

nodeLinker: node-modules

npmMinimalAgeGate: 3d

yarnPath: .yarn/releases/yarn-4.15.0.cjs
