#
# Your Crowdin credentials
#
project_id: '428892'
api_token_env: 'CROWDIN_PERSONAL_TOKEN'

base_path: '.'
base_url: 'https://api.crowdin.com'
preserve_hierarchy: true

# See Yaml anchors: https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/
languages_mapping: &languages_mapping
  locale:
    'es-ES': 'es-ES'
    'ja': 'ja'
    'pt-BR': 'pt-BR'
    'ro': 'ro'
    'ru': 'ru'
    'uk': 'uk'
    'zh-CN': 'zh-Hans'

#
# Files configuration
# see https://support.crowdin.com/configuration-file/
#
files:
  [
    {
      'source': '/website-v2/i18n/en/**/*',
      'translation': '/website-v2/i18n/%locale%/**/%original_file_name%',
      'languages_mapping': *languages_mapping,
    },
    {
      'source': '/docs/**/*',
      'translation': '/website-v2/i18n/%locale%/docusaurus-plugin-content-docs/current/**/%original_file_name%',
      'languages_mapping': *languages_mapping,
    },
    {
      'source': '/website-v2/versioned_docs/**/*',
      'translation': '/website-v2/i18n/%locale%/docusaurus-plugin-content-docs/**/%original_file_name%',
      'languages_mapping': *languages_mapping,
    },
    {
      'source': '/website/blog/**/*',
      'translation': '/website-v2/i18n/%locale%/docusaurus-plugin-content-blog/**/%original_file_name%',
      'languages_mapping': *languages_mapping,
    },
  ]
